language: node_js
node_js:
  - lts/dubnium
  - node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TFSCno8vRL2/rMZXidAfM2ayK3XjSZVmBfBsKDb6NlGqriltlSNVVO4Y3DLP6lfWmSlwM5niv7056GEEwXqvgBjzZZqFHLPDi/9DWqdCYB5HpAWR3qy/7FhArRYlS2CBe+6h8+ktAf1lXL0O4KjyIMznNKjy1DtX8VbMY1CmxPpV5wMBtGMacMGEPybP3j5degnI63Qdf6vnWeAfbQA1mVEOc5t83VRPrf4iCYtPHmJWm6KwjzoNJ7Xe3NHKPbR3TE6cBm/3j+aJjGxidyFwNH+b5MfPeyHznZHPPYAxvlyiSwo9PQGOfwyXXE+CqeTe7byWEQp/uZzfc8kIuv8erD68EqBkF0IVPF052Y7PON3p6EtlYl3R9EyK2SsYIkts7IwIfEzBiQnno8JaIoSuQt7F9//+uOgrefwCtAtRBbTxbUcHzPllkXuNK1gLkQOm2DuwE7jTTQjtlUYansmboXvhOj24PyL+4x8MfpRSc4fy6tAUj5NMdRcV+OTV3T1wI3D9NWKJ7g7PBXqJM9sZ5vURK9o7QhWW3gHxUQnwfMFLrZwt1oSS2LR+3OjnlvHDY8txRbNXaP5k4PSq7BkUNgj2nmiBA/eeqQIqNd3lyRf3NTr+15jfWRAG6jxgPD8xZjYkQ9xMgNh3JfXtpiUVN7zcinvgN55AoUAVE0WNJBI=
  file:
    - 'is-alphanumerical.js'
    - 'is-alphanumerical.min.js'
  on:
    tags: true
